resume_index:
    path:     /
    defaults: { _controller: "AppBundle:Resume:index" }
    methods:  GET

resume_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Resume:show" }
    methods:  GET

resume_new:
    path:     /new
    defaults: { _controller: "AppBundle:Resume:new" }
    methods:  [GET, POST]

resume_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Resume:edit" }
    methods:  [GET, POST]

resume_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Resume:delete" }
    methods:  DELETE
