AppBundle\Entity\Resume:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\ResumeRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        title:
            type: string
            length: 255
        description:
            type: text
    lifecycleCallbacks: {  }
